#############################################################################
# Makefile for building: synopsis
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  synopsis.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile synopsis.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-base \
		sub-dao \
		sub-dao-drivers-postgres \
		sub-dao-facade \
		sub-test


sub-base-qmake_all:  FORCE
	@test -d base/ || mkdir -p base/
	cd base/ && $(QMAKE) /home/qaz/work/synopsis2/base/base.pro -o Makefile
	cd base/ && $(MAKE) -f Makefile qmake_all
sub-base: FORCE
	@test -d base/ || mkdir -p base/
	cd base/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/base/base.pro -o Makefile ) && $(MAKE) -f Makefile
sub-base-make_first-ordered: FORCE
	@test -d base/ || mkdir -p base/
	cd base/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/base/base.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-base-make_first: FORCE
	@test -d base/ || mkdir -p base/
	cd base/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/base/base.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-base-all-ordered: FORCE
	@test -d base/ || mkdir -p base/
	cd base/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/base/base.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-base-all: FORCE
	@test -d base/ || mkdir -p base/
	cd base/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/base/base.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-base-clean-ordered: FORCE
	@test -d base/ || mkdir -p base/
	cd base/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/base/base.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-base-clean: FORCE
	@test -d base/ || mkdir -p base/
	cd base/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/base/base.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-base-distclean-ordered: FORCE
	@test -d base/ || mkdir -p base/
	cd base/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/base/base.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-base-distclean: FORCE
	@test -d base/ || mkdir -p base/
	cd base/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/base/base.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-base-install_subtargets-ordered: FORCE
	@test -d base/ || mkdir -p base/
	cd base/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/base/base.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-base-install_subtargets: FORCE
	@test -d base/ || mkdir -p base/
	cd base/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/base/base.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-base-uninstall_subtargets-ordered: FORCE
	@test -d base/ || mkdir -p base/
	cd base/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/base/base.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-base-uninstall_subtargets: FORCE
	@test -d base/ || mkdir -p base/
	cd base/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/base/base.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-dao-qmake_all: sub-base-qmake_all FORCE
	@test -d dao/ || mkdir -p dao/
	cd dao/ && $(QMAKE) /home/qaz/work/synopsis2/dao/dao.pro -o Makefile
	cd dao/ && $(MAKE) -f Makefile qmake_all
sub-dao: FORCE
	@test -d dao/ || mkdir -p dao/
	cd dao/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/dao.pro -o Makefile ) && $(MAKE) -f Makefile
sub-dao-make_first-ordered: sub-base-make_first-ordered  FORCE
	@test -d dao/ || mkdir -p dao/
	cd dao/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/dao.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-dao-make_first: FORCE
	@test -d dao/ || mkdir -p dao/
	cd dao/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/dao.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-dao-all-ordered: sub-base-all-ordered  FORCE
	@test -d dao/ || mkdir -p dao/
	cd dao/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/dao.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-dao-all: FORCE
	@test -d dao/ || mkdir -p dao/
	cd dao/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/dao.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-dao-clean-ordered: sub-base-clean-ordered  FORCE
	@test -d dao/ || mkdir -p dao/
	cd dao/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/dao.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-dao-clean: FORCE
	@test -d dao/ || mkdir -p dao/
	cd dao/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/dao.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-dao-distclean-ordered: sub-base-distclean-ordered  FORCE
	@test -d dao/ || mkdir -p dao/
	cd dao/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/dao.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-dao-distclean: FORCE
	@test -d dao/ || mkdir -p dao/
	cd dao/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/dao.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-dao-install_subtargets-ordered: sub-base-install_subtargets-ordered  FORCE
	@test -d dao/ || mkdir -p dao/
	cd dao/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/dao.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-dao-install_subtargets: FORCE
	@test -d dao/ || mkdir -p dao/
	cd dao/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/dao.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-dao-uninstall_subtargets-ordered: sub-base-uninstall_subtargets-ordered  FORCE
	@test -d dao/ || mkdir -p dao/
	cd dao/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/dao.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-dao-uninstall_subtargets: FORCE
	@test -d dao/ || mkdir -p dao/
	cd dao/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/dao.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-dao-drivers-postgres-qmake_all: sub-dao-qmake_all FORCE
	@test -d dao/drivers/postgres/ || mkdir -p dao/drivers/postgres/
	cd dao/drivers/postgres/ && $(QMAKE) /home/qaz/work/synopsis2/dao/drivers/postgres/postgres.pro -o Makefile
	cd dao/drivers/postgres/ && $(MAKE) -f Makefile qmake_all
sub-dao-drivers-postgres: FORCE
	@test -d dao/drivers/postgres/ || mkdir -p dao/drivers/postgres/
	cd dao/drivers/postgres/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/drivers/postgres/postgres.pro -o Makefile ) && $(MAKE) -f Makefile
sub-dao-drivers-postgres-make_first-ordered: sub-dao-make_first-ordered  FORCE
	@test -d dao/drivers/postgres/ || mkdir -p dao/drivers/postgres/
	cd dao/drivers/postgres/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/drivers/postgres/postgres.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-dao-drivers-postgres-make_first: FORCE
	@test -d dao/drivers/postgres/ || mkdir -p dao/drivers/postgres/
	cd dao/drivers/postgres/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/drivers/postgres/postgres.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-dao-drivers-postgres-all-ordered: sub-dao-all-ordered  FORCE
	@test -d dao/drivers/postgres/ || mkdir -p dao/drivers/postgres/
	cd dao/drivers/postgres/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/drivers/postgres/postgres.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-dao-drivers-postgres-all: FORCE
	@test -d dao/drivers/postgres/ || mkdir -p dao/drivers/postgres/
	cd dao/drivers/postgres/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/drivers/postgres/postgres.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-dao-drivers-postgres-clean-ordered: sub-dao-clean-ordered  FORCE
	@test -d dao/drivers/postgres/ || mkdir -p dao/drivers/postgres/
	cd dao/drivers/postgres/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/drivers/postgres/postgres.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-dao-drivers-postgres-clean: FORCE
	@test -d dao/drivers/postgres/ || mkdir -p dao/drivers/postgres/
	cd dao/drivers/postgres/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/drivers/postgres/postgres.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-dao-drivers-postgres-distclean-ordered: sub-dao-distclean-ordered  FORCE
	@test -d dao/drivers/postgres/ || mkdir -p dao/drivers/postgres/
	cd dao/drivers/postgres/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/drivers/postgres/postgres.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-dao-drivers-postgres-distclean: FORCE
	@test -d dao/drivers/postgres/ || mkdir -p dao/drivers/postgres/
	cd dao/drivers/postgres/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/drivers/postgres/postgres.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-dao-drivers-postgres-install_subtargets-ordered: sub-dao-install_subtargets-ordered  FORCE
	@test -d dao/drivers/postgres/ || mkdir -p dao/drivers/postgres/
	cd dao/drivers/postgres/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/drivers/postgres/postgres.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-dao-drivers-postgres-install_subtargets: FORCE
	@test -d dao/drivers/postgres/ || mkdir -p dao/drivers/postgres/
	cd dao/drivers/postgres/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/drivers/postgres/postgres.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-dao-drivers-postgres-uninstall_subtargets-ordered: sub-dao-uninstall_subtargets-ordered  FORCE
	@test -d dao/drivers/postgres/ || mkdir -p dao/drivers/postgres/
	cd dao/drivers/postgres/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/drivers/postgres/postgres.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-dao-drivers-postgres-uninstall_subtargets: FORCE
	@test -d dao/drivers/postgres/ || mkdir -p dao/drivers/postgres/
	cd dao/drivers/postgres/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/drivers/postgres/postgres.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-dao-facade-qmake_all: sub-dao-drivers-postgres-qmake_all FORCE
	@test -d dao/facade/ || mkdir -p dao/facade/
	cd dao/facade/ && $(QMAKE) /home/qaz/work/synopsis2/dao/facade/facade.pro -o Makefile
	cd dao/facade/ && $(MAKE) -f Makefile qmake_all
sub-dao-facade: FORCE
	@test -d dao/facade/ || mkdir -p dao/facade/
	cd dao/facade/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/facade/facade.pro -o Makefile ) && $(MAKE) -f Makefile
sub-dao-facade-make_first-ordered: sub-dao-drivers-postgres-make_first-ordered  FORCE
	@test -d dao/facade/ || mkdir -p dao/facade/
	cd dao/facade/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/facade/facade.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-dao-facade-make_first: FORCE
	@test -d dao/facade/ || mkdir -p dao/facade/
	cd dao/facade/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/facade/facade.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-dao-facade-all-ordered: sub-dao-drivers-postgres-all-ordered  FORCE
	@test -d dao/facade/ || mkdir -p dao/facade/
	cd dao/facade/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/facade/facade.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-dao-facade-all: FORCE
	@test -d dao/facade/ || mkdir -p dao/facade/
	cd dao/facade/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/facade/facade.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-dao-facade-clean-ordered: sub-dao-drivers-postgres-clean-ordered  FORCE
	@test -d dao/facade/ || mkdir -p dao/facade/
	cd dao/facade/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/facade/facade.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-dao-facade-clean: FORCE
	@test -d dao/facade/ || mkdir -p dao/facade/
	cd dao/facade/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/facade/facade.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-dao-facade-distclean-ordered: sub-dao-drivers-postgres-distclean-ordered  FORCE
	@test -d dao/facade/ || mkdir -p dao/facade/
	cd dao/facade/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/facade/facade.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-dao-facade-distclean: FORCE
	@test -d dao/facade/ || mkdir -p dao/facade/
	cd dao/facade/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/facade/facade.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-dao-facade-install_subtargets-ordered: sub-dao-drivers-postgres-install_subtargets-ordered  FORCE
	@test -d dao/facade/ || mkdir -p dao/facade/
	cd dao/facade/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/facade/facade.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-dao-facade-install_subtargets: FORCE
	@test -d dao/facade/ || mkdir -p dao/facade/
	cd dao/facade/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/facade/facade.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-dao-facade-uninstall_subtargets-ordered: sub-dao-drivers-postgres-uninstall_subtargets-ordered  FORCE
	@test -d dao/facade/ || mkdir -p dao/facade/
	cd dao/facade/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/facade/facade.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-dao-facade-uninstall_subtargets: FORCE
	@test -d dao/facade/ || mkdir -p dao/facade/
	cd dao/facade/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/facade/facade.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-test-qmake_all: sub-dao-facade-qmake_all FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && $(QMAKE) /home/qaz/work/synopsis2/test/test.pro -o Makefile
	cd test/ && $(MAKE) -f Makefile qmake_all
sub-test: FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/test/test.pro -o Makefile ) && $(MAKE) -f Makefile
sub-test-make_first-ordered: sub-dao-facade-make_first-ordered  FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/test/test.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-test-make_first: FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/test/test.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-test-all-ordered: sub-dao-facade-all-ordered  FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/test/test.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-test-all: FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/test/test.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-test-clean-ordered: sub-dao-facade-clean-ordered  FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/test/test.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-test-clean: FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/test/test.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-test-distclean-ordered: sub-dao-facade-distclean-ordered  FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/test/test.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-test-distclean: FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/test/test.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-test-install_subtargets-ordered: sub-dao-facade-install_subtargets-ordered  FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/test/test.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-test-install_subtargets: FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/test/test.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-test-uninstall_subtargets-ordered: sub-dao-facade-uninstall_subtargets-ordered  FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/test/test.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-test-uninstall_subtargets: FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/test/test.pro -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: synopsis.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		synopsis.pro
	$(QMAKE) -o Makefile synopsis.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
synopsis.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile synopsis.pro

qmake_all: sub-base-qmake_all sub-dao-qmake_all sub-dao-drivers-postgres-qmake_all sub-dao-facade-qmake_all sub-test-qmake_all FORCE

make_first: sub-base-make_first-ordered sub-dao-make_first-ordered sub-dao-drivers-postgres-make_first-ordered sub-dao-facade-make_first-ordered sub-test-make_first-ordered FORCE
all: sub-base-all-ordered sub-dao-all-ordered sub-dao-drivers-postgres-all-ordered sub-dao-facade-all-ordered sub-test-all-ordered FORCE
clean: sub-base-clean-ordered sub-dao-clean-ordered sub-dao-drivers-postgres-clean-ordered sub-dao-facade-clean-ordered sub-test-clean-ordered FORCE
distclean: sub-base-distclean-ordered sub-dao-distclean-ordered sub-dao-drivers-postgres-distclean-ordered sub-dao-facade-distclean-ordered sub-test-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-base-install_subtargets-ordered sub-dao-install_subtargets-ordered sub-dao-drivers-postgres-install_subtargets-ordered sub-dao-facade-install_subtargets-ordered sub-test-install_subtargets-ordered FORCE
uninstall_subtargets: sub-base-uninstall_subtargets-ordered sub-dao-uninstall_subtargets-ordered sub-dao-drivers-postgres-uninstall_subtargets-ordered sub-dao-facade-uninstall_subtargets-ordered sub-test-uninstall_subtargets-ordered FORCE

sub-base-check_ordered:
	@test -d base/ || mkdir -p base/
	cd base/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/base/base.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-dao-check_ordered: sub-base-check_ordered 
	@test -d dao/ || mkdir -p dao/
	cd dao/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/dao.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-dao-drivers-postgres-check_ordered: sub-dao-check_ordered 
	@test -d dao/drivers/postgres/ || mkdir -p dao/drivers/postgres/
	cd dao/drivers/postgres/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/drivers/postgres/postgres.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-dao-facade-check_ordered: sub-dao-drivers-postgres-check_ordered 
	@test -d dao/facade/ || mkdir -p dao/facade/
	cd dao/facade/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/dao/facade/facade.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-test-check_ordered: sub-dao-facade-check_ordered 
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /home/qaz/work/synopsis2/test/test.pro -o Makefile ) && $(MAKE) -f Makefile check
check: sub-base-check_ordered sub-dao-check_ordered sub-dao-drivers-postgres-check_ordered sub-dao-facade-check_ordered sub-test-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

